### ISSUE TITLE
Answering "Other" to license question raises exception

### ISSUE THREAD

**Issue by dstansby** [OpenAstronomy/packaging-guide#11]
```
What open-source license would you like to use for your package?
1 - BSD 3-Clause
2 - GNU GPL v3+
3 - Apache Software License 2.0
4 - BSD 2-Clause
5 - Other
> license [1]: 5
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/bin/pieceofcake", line 8, in <module>
    sys.exit(main())
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/pieceofcake/main.py", line 96, in main
    values[key] = value[click.prompt(BOLD + '> ' + prompt + END,
IndexError: list index out of range
```

**Comment by nabobalis** [comment]
This seems to happen on all numerical choices and only happens with pierceofcake. Calling cookiecutter directly and putting in 5 works as expected.

**Comment by bmorris3** [comment]
I'm also seeing this. Any help?

**Comment by nabobalis** [comment]
I think if you use cookiecutter instead of piece of cake to run the template, it should be ok.

**Comment by dstansby** [comment]
https://packaging-guide.openastronomy.org/en/latest/#using-the-template still says

> To use this, we recommend you use the [pieceofcake](https://pypi.org/project/pieceofcake/) wrapper which gives you more details on the questions.

**Comment by dstansby** [comment]
See https://github.com/OpenAstronomy/packaging-guide/issues/26 - I think RTD needs an update!
